### ISSUE TITLE
Fix replay game length not determined when an observer left instantly

### ISSUE THREAD

**Issue by AshenKyle** [ZephyrBlu/zephyrus-sc2-parser#19]
If a replay contains multiple users / observers and one of them disconnects during the loading screen and thus doesn't get into the game, they would trigger a `NNet.Game.SGameUserLeaveEvent` event at 0 gameloop.

I fixed this rudimentarily with the following code, but perhaps you might find a more cleaner way to do it:
parser.py:205
`if event['_event'] == 'NNet.Game.SGameUserLeaveEvent' and event['_userid']['m_userId'] == next(player['m_workingSetSlotId'] for player in player_info['m_playerList'] if player['m_result'] == 2):`

**Comment by AshenKyle** [comment]
This replay from the TSL6 replay pack is an example of it.

[serral vs dark g3.zip](https://github.com/ZephyrBlu/zephyrus-sc2-parser/files/5881943/serral.vs.dark.g3.zip)

**Comment by ZephyrBlu** [comment]
Hey! Thanks for the heads up. I'll look into it properly this evening and probably make a quick fix.

**Comment by ZephyrBlu** [comment]
Thanks a lot for the heads up on this issue. It's probably affected quite a lot of the tournament games I parse, but I would have only noticed the ones where an observer left at the very start of the game and caused an error.

I just made this commit [0] which works with that replay you supplied, so hopefully this error doesn't come up again.

[0] https://github.com/ZephyrBlu/zephyrus-sc2-parser/commit/ec4c353e468b7d49c69b1ab897a4a1edf6013ac7

Sorry it took me a while to get around to this. The $GME fiasco really distracted me last week.
